language: cpp
jobs:
  include:
    # linux
    - name: "ARCH=arm32_v5 LLVM=1 LLVM_IAS=1"
      env: ARCH=arm32_v5 LLVM=1 LLVM_IAS=1
    - name: "ARCH=arm32_v6"
      env: ARCH=arm32_v6
    - name: "ARCH=arm32_v7 LLVM=1"
      env: ARCH=arm32_v7 LLVM=1
    - name: "ARCH=arm64 LLVM=1 LLVM_IAS=1"
      env: ARCH=arm64 LLVM=1 LLVM_IAS=1
    - name: "ARCH=mips"
      env: ARCH=mips
    - name: "ARCH=mipsel LD=ld.lld"
      env: ARCH=mipsel LD=ld.lld
    - name: "ARCH=ppc32"
      env: ARCH=ppc32
    - name: "ARCH=ppc64"
      env: ARCH=ppc64
    - name: "ARCH=ppc64le LD=ld.lld"
      env: ARCH=ppc64le LD=ld.lld
    - name: "ARCH=riscv BOOT=false LLVM_IAS=1"
      env: ARCH=riscv BOOT=false LLVM_IAS=1
    - name: "ARCH=s390 BOOT=false"
      env: ARCH=s390 BOOT=false
    - name: "ARCH=x86 LLVM=1 LLVM_IAS=1"
      env: ARCH=x86 LLVM=1 LLVM_IAS=1
    - name: "ARCH=x86_64 LLVM=1 LLVM_IAS=1"
      env: ARCH=x86_64 LLVM=1 LLVM_IAS=1
    # linux (cron only)
    #
    # net-next (cron only)
    - name: "ARCH=arm32_v5 LLVM=1 LLVM_IAS=1 REPO=net-next"
      env: ARCH=arm32_v5 LLVM=1 LLVM_IAS=1 REPO=net-next
      if: type = cron
    - name: "ARCH=arm32_v6 REPO=net-next"
      env: ARCH=arm32_v6 REPO=net-next
      if: type = cron
    - name: "ARCH=arm32_v7 LLVM=1 REPO=net-next"
      env: ARCH=arm32_v7 LLVM=1 REPO=net-next
      if: type = cron
    - name: "ARCH=arm64 LLVM=1 REPO=net-next"
      env: ARCH=arm64 LLVM=1 REPO=net-next
      if: type = cron
    - name: "ARCH=mips REPO=net-next"
      env: ARCH=mips REPO=net-next
      if: type = cron
    - name: "ARCH=mipsel LD=ld.lld REPO=net-next"
      env: ARCH=mipsel LD=ld.lld REPO=net-next
      if: type = cron
    - name: "ARCH=ppc32 REPO=net-next"
      env: ARCH=ppc32 REPO=net-next
      if: type = cron
    - name: "ARCH=ppc64 REPO=net-next"
      env: ARCH=ppc64 REPO=net-next
      if: type = cron
    - name: "ARCH=ppc64le LD=ld.lld REPO=net-next"
      env: ARCH=ppc64le LD=ld.lld REPO=net-next
      if: type = cron
    - name: "ARCH=riscv BOOT=false LLVM_IAS=1 REPO=net-next"
      env: ARCH=riscv BOOT=false LLVM_IAS=1 REPO=net-next
      if: type = cron
    - name: "ARCH=s390 BOOT=false REPO=net-next"
      env: ARCH=s390 REPO=net-next BOOT=false
      if: type = cron
    - name: "ARCH=x86 LLVM=1 LLVM_IAS=1 REPO=net-next"
      env: ARCH=x86 LLVM=1 LLVM_IAS=1 REPO=net-next
      if: type = cron
    - name: "ARCH=x86_64 LLVM=1 LLVM_IAS=1 REPO=net-next"
      env: ARCH=x86_64 LLVM=1 LLVM_IAS=1 REPO=net-next
      if: type = cron
    # stable
    - name: "ARCH=arm32_v7 LLVM=1 REPO=5.4"
      env: ARCH=arm32_v7 LLVM=1 REPO=5.4
      if: type = cron
    - name: "ARCH=arm64 LLVM=1 REPO=5.4"
      env: ARCH=arm64 LLVM=1 REPO=5.4
      if: type = cron
    - name: "ARCH=mips LD=ld.lld REPO=5.4"
      env: ARCH=mips LD=ld.lld REPO=5.4
      if: type = cron
    - name: "ARCH=mipsel LD=ld.lld REPO=5.4"
      env: ARCH=mipsel LD=ld.lld REPO=5.4
      if: type = cron
    - name: "ARCH=ppc32 REPO=5.4"
      env: ARCH=ppc32 REPO=5.4
      if: type = cron
    - name: "ARCH=x86_64 LLVM=1 REPO=5.4"
      env: ARCH=x86_64 LLVM=1 REPO=5.4
      if: type = cron
    - name: "ARCH=arm32_v7 LLVM=1 REPO=4.19"
      env: ARCH=arm32_v7 LLVM=1 REPO=4.19
      if: type = cron
    - name: "ARCH=arm64 LLVM=1 REPO=4.19"
      env: ARCH=arm64 LLVM=1 REPO=4.19
      if: type = cron
    - name: "ARCH=ppc64le REPO=4.19"
      env: ARCH=ppc64le REPO=4.19
      if: type = cron
    - name: "ARCH=x86_64 LLVM=1 REPO=4.19"
      env: ARCH=x86_64 LLVM=1 REPO=4.19
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=4.14"
      env: ARCH=arm32_v7 REPO=4.14
      if: type = cron
    - name: "ARCH=arm64 LD=ld.lld REPO=4.14"
      env: ARCH=arm64 LD=ld.lld REPO=4.14
      if: type = cron
    - name: "ARCH=ppc64le REPO=4.14"
      env: ARCH=ppc64le REPO=4.14
      if: type = cron
    - name: "ARCH=x86_64 LD=ld.lld REPO=4.14"
      env: ARCH=x86_64 LD=ld.lld REPO=4.14
      if: type = cron
    - name: "ARCH=arm32_v7 REPO=4.9"
      env: ARCH=arm32_v7 REPO=4.9
      if: type = cron
    - name: "ARCH=arm64 REPO=4.9"
      env: ARCH=arm64 REPO=4.9
      if: type = cron
    - name: "ARCH=x86_64 LD=ld.lld REPO=4.9"
      env: ARCH=x86_64 LD=ld.lld REPO=4.9
      if: type = cron
    - name: "ARCH=arm64 REPO=4.4"
      env: ARCH=arm64 REPO=4.4
      if: type = cron
    - name: "ARCH=x86_64 LD=ld.lld REPO=4.4"
      env: ARCH=x86_64 LD=ld.lld REPO=4.4
      if: type = cron
    # kernel/common
    - name: "ARCH=arm64 REPO=android-4.9-q"
      env: ARCH=arm64 REPO=android-4.9-q
      if: type = cron
    - name: "ARCH=arm64 REPO=android-4.14-stable"
      env: ARCH=arm64 REPO=android-4.14-stable
      if: type = cron
    - name: "ARCH=arm64 LLVM=1 REPO=android-4.19-stable"
      env: ARCH=arm64 LLVM=1 REPO=android-4.19-stable
      if: type = cron
    - name: "ARCH=arm64 LLVM=1 REPO=android12-5.4"
      env: ARCH=arm64 LLVM=1 REPO=android12-5.4
      if: type = cron
    - name: "ARCH=arm64 LLVM=1 LLVM_IAS=1 REPO=android-mainline"
      env: ARCH=arm64 LLVM=1 LLVM_IAS=1 REPO=android-mainline
      if: type = cron
    - name: "ARCH=x86_64 LD=ld.lld REPO=android-4.9-q"
      env: ARCH=x86_64 LD=ld.lld REPO=android-4.9-q
      if: type = cron
    - name: "ARCH=x86_64 LD=ld.lld REPO=android-4.14-stable"
      env: ARCH=x86_64 LD=ld.lld REPO=android-4.14-stable
      if: type = cron
    - name: "ARCH=x86_64 LLVM=1 REPO=android-4.19-stable"
      env: ARCH=x86_64 LLVM=1 REPO=android-4.19-stable
      if: type = cron
    - name: "ARCH=x86_64 LLVM=1 REPO=android12-5.4"
      env: ARCH=x86_64 LLVM=1 REPO=android12-5.4
      if: type = cron
    - name: "ARCH=x86_64 LLVM=1 LLVM_IAS=1 REPO=android-mainline"
      env: ARCH=x86_64 LLVM=1 LLVM_IAS=1 REPO=android-mainline
      if: type = cron
    # linux with stable LLVM/Clang
    - name: "ARCH=arm32_v5 LD=ld.lld LLVM_VERSION=11"
      env: ARCH=arm32_v5 LD=ld.lld LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=arm32_v6 LLVM_VERSION=11"
      env: ARCH=arm32_v6 LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=arm32_v7 LD=ld.lld LLVM_VERSION=11"
      env: ARCH=arm32_v7 LD=ld.lld LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=arm64 LLVM_VERSION=11"
      env: ARCH=arm64 LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=mips LLVM_VERSION=11"
      env: ARCH=mips LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=mipsel LLVM_VERSION=11"
      env: ARCH=mipsel LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=ppc32 LLVM_VERSION=11"
      env: ARCH=ppc32 LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=ppc64 LLVM_VERSION=11"
      env: ARCH=ppc64 LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=ppc64le LLVM_VERSION=11"
      env: ARCH=ppc64le LLVM_VERSION=11
      if: type = cron
    - name: "ARCH=x86_64 LLVM_VERSION=11"
      env: ARCH=x86_64 LLVM_VERSION=11
      if: type = cron
compiler: gcc
os: linux
cache:
  directories:
    - .ccache
services:
  - docker
script:
  - |
    docker run \
        --env ARCH=${ARCH} \
        --env LD=${LD} \
        --env LLVM=${LLVM} \
        --env LLVM_IAS=${LLVM_IAS} \
        --env REPO=${REPO} \
        --env BOOT=${BOOT} \
        --rm \
        --workdir /travis \
        --volume ${TRAVIS_BUILD_DIR}:/travis \
        clangbuiltlinux/ubuntu:llvm${LLVM_VERSION:-12}-latest /bin/bash -c './env-setup.sh && ./driver.sh && ccache -s'
after_script:
  - sleep 1
notifications:
  email:
    recipients:
      - ietf.dmytro@shytyi.net
    on_success: never
    on_failure: always
    if: type = cron
